const tipo = new URLSearchParams(location.search).get('tipo') || 'corporativa';
const page = document.querySelector('#prototype');
const label = document.querySelector('#demo-label');
const toast = document.querySelector('#toast');
const settings = {
  corporativa: { name:'NORTE / CONSULTORÍA', accent:'#267a74', soft:'#dce8dd', html:corporativa },
  ecommerce: { name:'ATELIER 08', accent:'#925e31', soft:'#f1e2cd', html:ecommerce },
  blog: { name:'SÍNTESIS', accent:'#765bb0', soft:'#e5def0', html:blog },
  portafolio: { name:'MARA VEGA', accent:'#9c6726', soft:'#ebdebe', html:portafolio },
  landing: { name:'CÍRCULO / RESET', accent:'#bf4e79', soft:'#f0dce5', html:landing }
};
const current = settings[tipo] || settings.corporativa;
document.documentElement.style.setProperty('--accent', current.accent);
document.documentElement.style.setProperty('--soft', current.soft);
document.title = `${current.name} — Prototipo Lumina Dev`;
label.textContent = current.name;
page.innerHTML = current.html();
page.insertAdjacentHTML('beforeend', `<footer class="demo-footer"><span>DEMO / ${current.name} / 2026</span><a href="../index.html#proyectos">← Volver al catálogo</a></footer>`);
const demoProgress = document.querySelector('.demo-progress span');
const updateDemoProgress = () => {
  const total = document.documentElement.scrollHeight - window.innerHeight;
  demoProgress.style.width = `${total > 0 ? (window.scrollY / total) * 100 : 0}%`;
};
window.addEventListener('scroll', updateDemoProgress, { passive: true });
updateDemoProgress();
function nav(){return `<div class="wrap"><nav class="demo-nav"><b>${current.name}</b><div class="nav-links"><button data-message="Esta sección está simulada">Inicio</button><button data-message="Explora las secciones del prototipo">Servicios</button><button data-message="Formulario de contacto simulado">Contacto</button></div></nav></div>`}
function corporativa(){return `${nav()}<section class="wrap hero-demo"><div><span class="overline">CONSULTORÍA ESTRATÉGICA</span><h1>Decisiones que<br><em>mueven negocios.</em></h1><p>Ayudamos a empresas en crecimiento a convertir la complejidad en un plan que sí se puede ejecutar.</p><button class="button" data-message="Solicitud de asesoría iniciada (demo)">Agenda una conversación →</button></div><div class="hero-art-demo"><b>Claridad<br>para crecer.</b></div></section><section class="wrap stats"><div><b>+48</b><span>PROYECTOS ACTIVADOS</span></div><div><b>12 años</b><span>EXPERIENCIA DE EQUIPO</span></div><div><b>94%</b><span>CLIENTES RECURRENTES</span></div></section><section class="wrap showcase"><h2 class="section-title">Expertise que se<br><em>traduce en avance.</em></h2><div class="feature-grid"><article class="feature"><i>01</i><b>Estrategia</b><p>Definimos el siguiente movimiento con foco, datos y personas reales.</p></article><article class="feature"><i>02</i><b>Transformación</b><p>Diseñamos procesos que hacen más liviano el trabajo complejo.</p></article><article class="feature"><i>03</i><b>Crecimiento</b><p>Convertimos buenas ideas en sistemas que escalan.</p></article></div></section><section class="cta"><h2>¿Listos para el siguiente capítulo?</h2><p>Construyamos un plan que sea tan claro como ambicioso.</p><button class="button" data-message="Gracias. Te contactaremos pronto (demo).">Hablemos →</button></section>`}
function ecommerce(){return `${nav()}<section class="wrap product-section"><div class="hero-demo"><div><span class="overline">OBJETOS PARA EL RITUAL DIARIO</span><h1>Menos, pero<br><em>mejor.</em></h1><p>Piezas honestas hechas para acompañarte mucho tiempo.</p><button class="button" data-message="Catálogo seleccionado (demo)">Ver colección →</button></div><div class="hero-art-demo"><b>Everyday<br>objects.</b></div></div><div class="product-toolbar"><h1>Selección de hoy</h1><button class="cart-pill" data-message="Tu carrito está vacío (demo)">BOLSA <span class="cart-count">0</span></button></div><div class="product-grid">${['Jarra Nido','Vela Umbral','Set Lino'].map((p,i)=>`<article class="product"><div class="product-image"></div><h2>${p}</h2><p>Materiales naturales · Edición limitada</p><div class="product-foot"><b>$${[68,38,54][i]}.000</b><button class="add-cart" data-product="${p}">Añadir +</button></div></article>`).join('')}</div></section><section class="cta"><h2>Diseñado para formar parte de tu vida.</h2><p>Envíos a toda Colombia · Cambios sin preguntas.</p></section>`}
function blog(){return `${nav()}<section class="wrap editorial-hero"><div><span class="overline">IDEAS PARA VER MÁS CLARO</span><h1>Una pausa para<br><em>pensar mejor.</em></h1><p>Ensayos, conversaciones e ideas prácticas para construir una vida y un trabajo más intencionales.</p><button class="button" data-message="Suscripción activada (demo)">Recibir el próximo ensayo</button></div><aside class="editorial-card"><span class="overline">DESTACADO / 06 MIN</span><b>La atención es<br>un lugar que<br>se diseña.</b></aside></section><section class="wrap"><div class="filters"><button class="filter active" data-filter="all">Todo</button><button class="filter" data-filter="trabajo">Trabajo</button><button class="filter" data-filter="vida">Vida</button></div><div class="article-grid">${[['trabajo','La energía que protege tu mejor trabajo'],['vida','Aprender a vivir en un ritmo propio'],['trabajo','Hacer espacio para las preguntas correctas']].map(x=>`<article class="article" data-category="${x[0]}"><div class="article-img"></div><span>${x[0].toUpperCase()} · 05 MIN</span><h2>${x[1]}</h2><p>Una lectura breve para regresar a lo que importa.</p><button class="filter" data-message="Artículo abierto (demo)">Leer ensayo →</button></article>`).join('')}</div></section><section class="cta"><h2>Una idea útil, cada dos semanas.</h2><p>Sin ruido. Solo cosas que vale la pena guardar.</p></section>`}
function portafolio(){return `${nav()}<section class="wrap portfolio-hero"><span class="overline">DIRECCIÓN CREATIVA / 2026</span><h1>Diseño con<br><i>pulso propio.</i></h1><p>Seleccionamos proyectos que combinan estrategia, carácter y una obsesión sana por el detalle.</p><div class="filters"><button class="filter active" data-filter="all">Todos</button><button class="filter" data-filter="identidad">Identidad</button><button class="filter" data-filter="digital">Digital</button></div></section><section class="wrap work-grid">${[['identidad','Casa Nativa'],['digital','Nómada'],['identidad','Salina'],['digital','Objeto 01']].map(x=>`<article class="work" data-category="${x[0]}"><span>${x[0].toUpperCase()} / 2026</span><b>${x[1]}</b></article>`).join('')}</section><section class="cta"><h2>Una buena idea merece una forma memorable.</h2><button class="button" data-message="Tu mensaje fue preparado (demo)">Iniciar proyecto →</button></section>`}
function landing(){return `${nav()}<section class="lead-hero"><div class="wrap"><span class="overline">UN RESET DE 14 DÍAS</span><h1>Vuelve a tu centro.<br><em>Sin irte lejos.</em></h1><p>Un programa suave y práctico para recuperar energía, enfoque y un ritmo que puedas sostener.</p><button class="button" data-scroll-form="true">Quiero empezar →</button></div></section><section class="proof"><div><b>4.9/5</b><span>VALORACIÓN MEDIA</span></div><div><b>+2.400</b><span>PERSONAS ACOMPAÑADAS</span></div><div><b>14 días</b><span>PARA RESTABLECER</span></div></section><section class="wrap lead-features"><div><b>01 / Respira</b><p>Pequeñas prácticas para despejar el ruido y recuperar espacio mental.</p></div><div><b>02 / Ajusta</b><p>Un método simple para organizar tu energía, no solo tu agenda.</p></div><div><b>03 / Sostén</b><p>Herramientas que te acompañan más allá de estas dos semanas.</p></div></section><section id="lead-form" class="cta"><h2>Empieza con una decisión pequeña.</h2><p>Recibe la primera guía directamente en tu correo.</p><form class="lead-form"><input required type="email" placeholder="Tu correo electrónico"><button class="button" type="submit">Recibir mi guía gratuita →</button></form></section>`}
function notify(message){toast.textContent=message;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2600)}
document.addEventListener('click',(e)=>{const btn=e.target.closest('[data-message]');if(btn)notify(btn.dataset.message);if(e.target.closest('[data-scroll-form]'))document.querySelector('#lead-form')?.scrollIntoView({behavior:'smooth'});if(e.target.closest('.add-cart')){const count=document.querySelector('.cart-count');count.textContent=Number(count.textContent)+1;notify(`${e.target.dataset.product} se añadió a la bolsa (demo)`)}if(e.target.matches('.filter[data-filter]')){document.querySelectorAll('.filter[data-filter]').forEach(x=>x.classList.remove('active'));e.target.classList.add('active');const f=e.target.dataset.filter;document.querySelectorAll('[data-category]').forEach(x=>x.classList.toggle('hide',f!=='all'&&x.dataset.category!==f))}});
document.addEventListener('submit',(e)=>{if(e.target.matches('.lead-form')){e.preventDefault();notify('¡Listo! La guía está en camino (simulado).')}});
